version: '3.1'

services:
  r1:
    build: 
      dockerfile: images/router.dockerfile
      context: .
    volumes:
      - ./volumes/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    ports:
      #admin
      - 10101:2601
      #ospf ipv4
      - 10102:2604    
    networks:
      r1-dns:
        ipv4_address: 192.168.2.10
      r1-ingress:
        ipv4_address: 192.168.1.10
      r1-hosts:
        ipv4_address: 192.168.3.10  
  
#   root-dns:
#     build: 
#       dockerfile: images/dns.dockerfile
#       context: .
#     volumes:
#       - ./bindconfig/nsroot/:/etc/bind:ro
#     ports:
#       - "10010:53/tcp"
#     networks:
#       r1-dns:
#         ipv4_address: 192.168.2.11

  host1: 
    build:
      dockerfile: images/host.dockerfile
      context: .
    volumes: 
      - ./volumes/resolv_com.conf:/etc/resolv.conf:ro
    command: tail -f /dev/null
    networks:
      r1-hosts:
        ipv4_address: 192.168.3.12

networks:
  r1-dns:      
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.2.0/24
  r1-ingress:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24
  r1-hosts:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.3.0/24