---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongo
spec:
  #type: LoadBalancer
  ports:
  - port: 27017
    #targetPort: 80
    #protocol: TCP
    name: mongo
  selector:
    app: mongo