---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
        app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: DATABASE_USERNAME
          value: strapi
        - name: DATABASE_PASSWORD
          value: strapi
        ports:
        - containerPort: 27017
        name: mongo