apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: strapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: redestp6.com
    http:
      paths:
        - path: /
          backend:
            serviceName: strapi-svc
            servicePort: 1337